version: '3.1'

services:
  db:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: food-challenge
      POSTGRES_DB: self-service
      POSTGRES_PASSWORD: root

  app:
    depends_on: [db]
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"