apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: food-challenge-db
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: food-challenge-db
  minReplicas: 1
  maxReplicas: 3
  targetCPUUtilizationPercentage: 70