kind: PersistentVolume
apiVersion: v1
metadata:
  name: food-challenge-pv
  labels:
    app: food-challenge-db
spec:
  storageClassName: manual
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/mnt/data"