kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: food-challenge-pvc
  labels:
    app: food-challenge-db
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi