apiVersion: v1
kind: Service
metadata:
  name: food-challenge-db
  labels:
    app: food-challenge-db
spec:
  selector:
    app: food-challenge-db
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432