apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: food-challenge
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: food-challenge
  minReplicas: 1
  maxReplicas: 10
  targetCPUUtilizationPercentage: 70