apiVersion: v1
kind: Service
metadata:
  name: food-challenge
  labels:
    app: food-challenge
spec:
  selector:
    app: food-challenge
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080